name: tele Userbot

on:
  workflow_dispatch: 
  schedule:
    - cron: "0 */6 * * *" # Otomatis jalan ulang tiap 6 jam biar bot gak mati kelamaan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # Mempercepat proses install jika ada cache

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Benxx Userbot
        env:
          
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
        run: python main.py
